@extends('layouts.app')
@section('title', 'My CQI Reports')

@section('breadcrumbs')
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ route('faculty.dashboard') }}">Dashboard</a></li>
    <li class="breadcrumb-item active">My CQI Reports</li>
</ol>
@endsection

@section('content')

<div class="page-header">
    <div>
        <h2 class="page-heading">My CQI Reports</h2>
        <p class="page-subheading">AI-generated Continuous Quality Improvement reports for your courses.</p>
    </div>
</div>

<div class="card">
    @if ($reports->isEmpty())
        <div class="empty-state">
            <div class="empty-state-icon"><i class="bi bi-clipboard-data"></i></div>
            <p class="empty-state-text">No CQI reports have been generated for your courses yet.</p>
            <p class="text-muted-sm text-center" style="max-width: 320px;">
                Reports are generated by the administrator after surveys are closed and analytics are computed.
            </p>
        </div>
    @else
        <div class="table-responsive">
            <table class="table data-table align-middle mb-0">
                <thead>
                    <tr>
                        <th>Course</th>
                        <th>Semester</th>
                        <th>Scope</th>
                        <th>Generated</th>
                        <th class="text-end">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($reports as $report)
                    <tr>
                        <td>
                            <div class="d-flex align-items-center gap-2">
                                <div class="cqi-report-icon">
                                    <i class="bi bi-file-earmark-bar-graph"></i>
                                </div>
                                <div>
                                    <div class="fw-500 text-mono" style="font-size:.82rem;">
                                        {{ $report->survey?->offering?->subject?->course_code }}
                                    </div>
                                    <div class="text-muted-sm">
                                        {{ Str::limit($report->survey?->offering?->subject?->name, 36) }}
                                    </div>
                                </div>
                            </div>
                        </td>
                        <td class="text-muted-sm">
                            {{ $report->survey?->offering?->semester?->full_label ?? '—' }}
                        </td>
                        <td>
                            <span class="scope-badge scope-badge--{{ $report->scope_type }}">
                                {{ ucfirst($report->scope_type) }}
                            </span>
                        </td>
                        <td class="text-muted-sm">{{ $report->created_at->format('M d, Y') }}</td>
                        <td class="text-end">
                            <div class="table-actions">
                                <a href="{{ route('faculty.reports.show', $report->id) }}"
                                   class="btn btn-sm btn-icon" title="View Report">
                                    <i class="bi bi-eye"></i>
                                </a>
                                <a href="{{ route('faculty.reports.download', $report->id) }}"
                                   class="btn btn-sm btn-icon" title="Download PDF">
                                    <i class="bi bi-download"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        @if ($reports->hasPages())
            <div class="table-pagination">{{ $reports->links() }}</div>
        @endif
    @endif
</div>

@endsection