{{-- resources/views/admin/cqi-reports/index.blade.php --}}
@extends('admin.layouts.app')
@section('title', 'CQI Reports')

@section('content')
<div class="page-header">
    <h1>CQI Reports</h1>
</div>

<form method="GET" action="{{ route('admin.cqi-reports.index') }}">
    <div class="filters">
        <select name="semester_id" class="form-control" style="min-width:220px;">
            <option value="">All Semesters</option>
            @foreach ($semesters as $sem)
                <option value="{{ $sem->id }}" @selected($selectedSemesterId == $sem->id)>
                    {{ $sem->full_label }} {{ $sem->is_active ? '(Active)' : '' }}
                </option>
            @endforeach
        </select>
        <input type="text" name="search" class="form-control" placeholder="Search title…" value="{{ request('search') }}">
        <select name="status" class="form-control">
            <option value="">Active</option>
            <option value="deleted" @selected(request('status') === 'deleted')>Archived</option>
            <option value="all"     @selected(request('status') === 'all')>All</option>
        </select>
        <button type="submit" class="btn btn-secondary">Filter</button>
        <a href="{{ route('admin.cqi-reports.index') }}" class="btn btn-secondary">Clear</a>
    </div>
</form>

<div class="card">
    @if ($reports->isEmpty())
        <p class="empty-state">No CQI reports generated yet.</p>
    @else
        <table>
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Scope</th>
                    <th>Faculty</th>
                    <th>Semester</th>
                    <th>Generated By</th>
                    <th>Generated At</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($reports as $report)
                <tr class="{{ $report->trashed() ? 'archived' : '' }}">
                    <td>
                        <div style="font-weight:500;font-size:.875rem;">{{ $report->title }}</div>
                        @if ($report->is_regenerated)
                            <span style="font-size:.7rem;background:#fef3c7;color:#92400e;padding:.1rem .4rem;border-radius:4px;">Regenerated</span>
                        @endif
                    </td>
                    <td><span class="badge badge-default" style="text-transform:uppercase;font-size:.7rem;">{{ $report->scope_type }}</span></td>
                    <td style="font-size:.82rem;">{{ $report->faculty?->name ?? '—' }}</td>
                    <td style="font-size:.8rem;">{{ $report->survey?->offering?->semester?->full_label ?? '—' }}</td>
                    <td style="font-size:.82rem;">{{ $report->generatedBy?->name ?? '—' }}</td>
                    <td style="font-size:.78rem;color:#6b7280;">{{ $report->created_at->format('M d, Y h:i A') }}</td>
                    <td>
                        <div class="actions">
                            @if (! $report->trashed())
                                <a href="{{ route('admin.cqi-reports.show', $report->id) }}" class="btn btn-sm btn-secondary">View</a>
                                <a href="{{ route('admin.cqi-reports.download', $report->id) }}" class="btn btn-sm btn-primary">↓ PDF</a>
                                <form method="POST" action="{{ route('admin.cqi-reports.send-to-faculty', $report->id) }}">
                                    @csrf
                                    <button class="btn btn-sm btn-success">Send to Faculty</button>
                                </form>
                                <form method="POST" action="{{ route('admin.cqi-reports.destroy', $report->id) }}" onsubmit="return confirm('Archive this report?')">
                                    @csrf @method('DELETE')
                                    <button class="btn btn-sm btn-danger">Archive</button>
                                </form>
                            @endif
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <div class="pagination">{{ $reports->links('pagination::simple-tailwind') }}</div>
    @endif
</div>
@endsection
