@if ($reports->isEmpty())
    <div class="empty-state">
        <div class="empty-state-icon"><i class="bi bi-clipboard-data"></i></div>
        <p class="empty-state-text">No CQI reports generated yet.</p>
        <p class="text-muted-sm text-center" style="max-width: 340px;">
            Generate reports from the Analytics detail page after a survey is deactivated.
        </p>
    </div>
@else
    <div class="table-responsive">
        <table class="table data-table align-middle mb-0">
            <thead>
                <tr>
                    <th>Report</th>
                    {{-- <th>Scope</th> --}}
                    <th>Faculty</th>
                    <th>Semester</th>
                    <th>Generated By</th>
                    <th>Generated At</th>
                    <th class="text-end">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($reports as $report)
                <tr class="{{ $report->trashed() ? 'row-muted' : '' }}">
                    <td>
                        <div class="d-flex align-items-center gap-2">
                            <div class="cqi-report-icon"><i class="bi bi-file-earmark-bar-graph"></i></div>
                            <div>
                                <div class="fw-500">{{ $report->title }}</div>
                                @if ($report->is_regenerated)
                                    <span class="regen-badge"><i class="bi bi-arrow-repeat me-1"></i>Regenerated</span>
                                @endif
                            </div>
                        </div>
                    </td>
                    {{-- <td>
                        <span class="scope-badge scope-badge--{{ $report->scope_type }}">
                            {{ ucfirst($report->scope_type) }}
                        </span>
                    </td> --}}
                    <td>
                        @if ($report->faculty)
                            <div class="user-cell">
                                {{-- <div class="user-avatar-sm" style="width:26px;height:26px;font-size:.6rem;">
                                    {{ strtoupper(substr($report->faculty->name, 0, 2)) }}
                                </div> --}}
                                <span class="text-muted-sm">{{ $report->faculty->name }}</span>
                            </div>
                        @else
                            <span class="text-muted-sm">—</span>
                        @endif
                    </td>
                    <td class="text-muted-sm">{{ $report->survey?->offering?->semester?->full_label ?? '—' }}</td>
                    <td class="text-muted-sm">{{ $report->generatedBy?->name ?? '—' }}</td>
                    <td class="text-muted-sm">{{ $report->created_at->format('M d, Y') }}</td>
                    <td class="text-end">
                        @if (! $report->trashed())
                        @php
                            $isSent = $report->logs->contains('action', 'sent_to_faculty');
                        @endphp
                            <div class="table-actions">
                                <a href="{{ route('admin.cqi-reports.show', $report->id) }}" class="btn btn-sm btn-icon" title="View"><i class="bi bi-eye"></i></a>
                                <a href="{{ route('admin.cqi-reports.download', $report->id) }}" class="btn btn-sm btn-icon" title="Download"><i class="bi bi-download"></i></a>
                                @if($isSent)
                                    {{-- Show a disabled checkmark or a 'Sent' indicator --}}
                                    <button type="button" class="btn btn-sm btn-icon text-success" title="Already Sent" disabled>
                                        <i class="bi bi-check-circle-fill"></i>
                                    </button>
                                @else
                                    {{-- Show the active Send button --}}
                                    <form method="POST" action="{{ route('admin.cqi-reports.send-to-faculty', $report->id) }}" class="d-inline" data-confirm="Send this report to {{ $report->faculty?->name ?? 'faculty' }}?">
                                        @csrf
                                        <button type="submit" class="btn btn-sm btn-icon btn-icon--success" title="Send to Faculty">
                                            <i class="bi bi-send"></i>
                                        </button>
                                    </form>
                                @endif
                                <form method="POST" action="{{ route('admin.cqi-reports.destroy', $report->id) }}" class="d-inline" data-confirm="Archive this CQI report?">
                                    @csrf @method('DELETE')
                                    <button type="submit" class="btn btn-sm btn-icon btn-icon--danger"><i class="bi bi-archive"></i></button>
                                </form>
                            </div>
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @if ($reports->hasPages())
        <div class="table-pagination mt-3">
            {{ $reports->links() }}
        </div>
    @endif
@endif