@extends('layouts.app')
@section('title', 'CQI Reports')

@section('breadcrumbs')
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
    <li class="breadcrumb-item active">CQI Reports</li>
</ol>
@endsection

@section('content')

<div class="page-header">
    <div>
        <h2 class="page-heading">CQI Reports</h2>
        <p class="page-subheading">AI-generated Continuous Quality Improvement reports for faculty.</p>
    </div>
</div>

{{-- ===== FILTERS ===== --}}
<div class="card filter-card mb-3">
    <div class="card-body">
        <form method="GET" action="{{ route('admin.cqi-reports.index') }}">
            <div class="row g-3 align-items-end">

                <div class="col-md-3">
                    <label class="form-label">Semester</label>
                    <select name="semester_id" class="form-select">
                        <option value="">All Semesters</option>
                        @foreach ($semesters as $sem)
                            <option value="{{ $sem->id }}" @selected($selectedSemesterId == $sem->id)>
                                {{ $sem->full_label }}{{ $sem->is_active ? ' · Active' : '' }}
                            </option>
                        @endforeach
                    </select>
                </div>

                <div class="col-md-3">
                    <label class="form-label">Search</label>
                    <div class="input-icon-wrap">
                        <i class="bi bi-search input-icon"></i>
                        <input type="text" name="search" class="form-control auth-input"
                               placeholder="Search title…" value="{{ request('search') }}">
                    </div>
                </div>

                <div class="col-md-2">
                    <label class="form-label">Status</label>
                    <select name="status" class="form-select">
                        <option value="">Active</option>
                        <option value="deleted" @selected(request('status') === 'deleted')>Archived</option>
                        <option value="all"     @selected(request('status') === 'all')>All</option>
                    </select>
                </div>

                <div class="col-md-4 d-flex gap-2">
                    <button type="submit" class="btn btn-primary">
                        <i class="bi bi-funnel me-1"></i> Filter
                    </button>
                    <a href="{{ route('admin.cqi-reports.index') }}" class="btn btn-outline-secondary">
                        <i class="bi bi-x-lg me-1"></i> Reset
                    </a>
                </div>

            </div>
        </form>
    </div>
</div>

{{-- ===== TABLE ===== --}}
<div class="card">
    @if ($reports->isEmpty())
        <div class="empty-state">
            <div class="empty-state-icon"><i class="bi bi-clipboard-data"></i></div>
            <p class="empty-state-text">No CQI reports generated yet.</p>
            <p class="text-muted-sm text-center" style="max-width: 340px;">
                Generate reports from the Analytics detail page after a survey is deactivated.
            </p>
        </div>
    @else
        <div class="table-responsive">
            <table class="table data-table align-middle mb-0">
                <thead>
                    <tr>
                        <th>Report</th>
                        <th>Scope</th>
                        <th>Faculty</th>
                        <th>Semester</th>
                        <th>Generated By</th>
                        <th>Generated At</th>
                        <th class="text-end">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($reports as $report)
                    <tr class="{{ $report->trashed() ? 'row-muted' : '' }}">

                        <td>
                            <div class="d-flex align-items-center gap-2">
                                <div class="cqi-report-icon">
                                    <i class="bi bi-file-earmark-bar-graph"></i>
                                </div>
                                <div>
                                    <div class="fw-500">{{ $report->title }}</div>
                                    @if ($report->is_regenerated)
                                        <span class="regen-badge">
                                            <i class="bi bi-arrow-repeat me-1"></i>Regenerated
                                        </span>
                                    @endif
                                </div>
                            </div>
                        </td>

                        <td>
                            <span class="scope-badge scope-badge--{{ $report->scope_type }}">
                                {{ ucfirst($report->scope_type) }}
                            </span>
                        </td>

                        <td>
                            @if ($report->faculty)
                                <div class="user-cell">
                                    <div class="user-avatar-sm" style="width:26px;height:26px;font-size:.6rem;">
                                        {{ strtoupper(substr($report->faculty->name, 0, 2)) }}
                                    </div>
                                    <span class="text-muted-sm">{{ $report->faculty->name }}</span>
                                </div>
                            @else
                                <span class="text-muted-sm">—</span>
                            @endif
                        </td>

                        <td class="text-muted-sm">
                            {{ $report->survey?->offering?->semester?->full_label ?? '—' }}
                        </td>

                        <td class="text-muted-sm">
                            {{ $report->generatedBy?->name ?? '—' }}
                        </td>

                        <td class="text-muted-sm">
                            {{ $report->created_at->format('M d, Y') }}
                        </td>

                        <td class="text-end">
                            @if (! $report->trashed())
                                <div class="table-actions">

                                    <a href="{{ route('admin.cqi-reports.show', $report->id) }}"
                                       class="btn btn-sm btn-icon" title="View Report">
                                        <i class="bi bi-eye"></i>
                                    </a>

                                    <a href="{{ route('admin.cqi-reports.download', $report->id) }}"
                                       class="btn btn-sm btn-icon" title="Download PDF">
                                        <i class="bi bi-download"></i>
                                    </a>

                                    <form method="POST"
                                          action="{{ route('admin.cqi-reports.send-to-faculty', $report->id) }}"
                                          class="d-inline"
                                          data-confirm="Send this CQI report to {{ $report->faculty?->name }}?">
                                        @csrf
                                        <button type="submit" class="btn btn-sm btn-icon btn-icon--success"
                                                title="Send to Faculty">
                                            <i class="bi bi-send"></i>
                                        </button>
                                    </form>

                                    <form method="POST"
                                          action="{{ route('admin.cqi-reports.destroy', $report->id) }}"
                                          class="d-inline"
                                          data-confirm="Archive this CQI report?">
                                        @csrf @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-icon btn-icon--danger"
                                                title="Archive">
                                            <i class="bi bi-archive"></i>
                                        </button>
                                    </form>

                                </div>
                            @endif
                        </td>

                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        @if ($reports->hasPages())
            <div class="table-pagination">{{ $reports->links() }}</div>
        @endif
    @endif
</div>

@endsection

@push('scripts')
<script src="{{ asset('js/modules/confirm-action.js') }}"></script>
@endpush