@extends('layouts.app')
@section('title', 'CQI Report — ' . $cqiReport->title)

@section('breadcrumbs')
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{ route('admin.cqi-reports.index') }}">CQI Reports</a></li>
    <li class="breadcrumb-item active">{{ Str::limit($cqiReport->title, 40) }}</li>
</ol>
@endsection

@section('content')

@php $ai = $cqiReport->report_text; @endphp

{{-- ===== PAGE HEADER ===== --}}
<div class="page-header flex-wrap gap-2">
    <div>
        <h2 class="page-heading">CQI Report</h2>
        <p class="page-subheading">{{ $cqiReport->title }}</p>
    </div>
    <div class="d-flex flex-wrap gap-2">
        <a href="{{ route('admin.cqi-reports.download', $cqiReport->id) }}"
           class="btn btn-sm btn-primary">
            <i class="bi bi-download me-1"></i> Download PDF
        </a>
        <form method="POST"
              action="{{ route('admin.cqi-reports.send-to-faculty', $cqiReport->id) }}"
              data-confirm="Mark this report as sent to {{ $cqiReport->faculty?->name }}?">
            @csrf
            <button type="submit" class="btn btn-sm btn-outline-secondary">
                <i class="bi bi-send me-1"></i> Send to Faculty
            </button>
        </form>
        <a href="{{ route('admin.cqi-reports.index') }}" class="btn btn-sm btn-outline-secondary">
            <i class="bi bi-arrow-left me-1"></i> Back
        </a>
    </div>
</div>

{{-- ===== META + SCOPE GRID ===== --}}
<div class="cqi-meta-grid mb-4">

    {{-- Report meta card --}}
    <div class="card">
        <div class="card-body p-0">
            <div class="detail-row">
                <span class="detail-label"><i class="bi bi-person-workspace me-2 text-muted"></i>Faculty</span>
                <span class="detail-value fw-500">{{ $cqiReport->faculty?->name ?? '—' }}</span>
            </div>
            <div class="detail-row">
                <span class="detail-label"><i class="bi bi-book me-2 text-muted"></i>Course</span>
                <span class="detail-value">
                    {{ $cqiReport->survey?->offering?->subject?->course_code }}
                    — {{ $cqiReport->survey?->offering?->subject?->name }}
                </span>
            </div>
            <div class="detail-row">
                <span class="detail-label"><i class="bi bi-calendar3 me-2 text-muted"></i>Semester</span>
                <span class="detail-value">{{ $cqiReport->survey?->offering?->semester?->full_label }}</span>
            </div>
            <div class="detail-row">
                <span class="detail-label"><i class="bi bi-layers me-2 text-muted"></i>Scope</span>
                <span class="detail-value">
                    <span class="scope-badge scope-badge--{{ $cqiReport->scope_type }}">
                        {{ ucfirst($cqiReport->scope_type) }}
                    </span>
                </span>
            </div>
            <div class="detail-row">
                <span class="detail-label"><i class="bi bi-robot me-2 text-muted"></i>AI Model</span>
                <span class="detail-value text-muted-sm">
                    {{ $cqiReport->model_name }} / {{ $cqiReport->model_version }}
                </span>
            </div>
            <div class="detail-row detail-row--last">
                <span class="detail-label"><i class="bi bi-person-check me-2 text-muted"></i>Generated By</span>
                <span class="detail-value text-muted-sm">
                    {{ $cqiReport->generatedBy?->name }}
                    · {{ $cqiReport->created_at->format('M d, Y h:i A') }}
                </span>
            </div>
        </div>
    </div>

    {{-- AI badge card --}}
    <div class="cqi-ai-badge-card">
        <div class="cqi-ai-badge-card__glow"></div>
        <div class="cqi-ai-badge-card__inner">
            <div class="cqi-ai-badge-card__icon">
                <i class="bi bi-robot"></i>
            </div>
            <p class="cqi-ai-badge-card__label">AI-Generated Report</p>
            <p class="cqi-ai-badge-card__model">
                {{ $cqiReport->model_name }}
            </p>
            <p class="cqi-ai-badge-card__date">
                {{ $cqiReport->created_at->format('F j, Y') }}
            </p>
        </div>
    </div>

</div>

{{-- ===== OVERALL INTERPRETATION ===== --}}
@if (isset($ai['overall_interpretation']))
<div class="cqi-section cqi-section--interpretation mb-4">
    <div class="cqi-section__header">
        <div class="cqi-section__icon cqi-section__icon--blue">
            <i class="bi bi-lightbulb"></i>
        </div>
        <h3 class="cqi-section__title">Overall Interpretation</h3>
    </div>
    <p class="cqi-section__body">{{ $ai['overall_interpretation'] }}</p>
</div>
@endif

{{-- ===== STRENGTHS + AREAS FOR IMPROVEMENT ===== --}}
<div class="row g-3 mb-4">

    @if (!empty($ai['strengths']))
    <div class="col-md-6">
        <div class="card cqi-list-card cqi-list-card--strengths h-100">
            <div class="card-body">
                <div class="cqi-list-card__header">
                    <div class="cqi-list-card__icon cqi-list-card__icon--green">
                        <i class="bi bi-check-circle-fill"></i>
                    </div>
                    <h5 class="cqi-list-card__title">Strengths</h5>
                </div>
                <ul class="cqi-bullet-list">
                    @foreach ($ai['strengths'] as $s)
                        <li class="cqi-bullet-list__item cqi-bullet-list__item--green">
                            {{ $s }}
                        </li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
    @endif

    @if (!empty($ai['areas_for_improvement']))
    <div class="col-md-6">
        <div class="card cqi-list-card cqi-list-card--improvement h-100">
            <div class="card-body">
                <div class="cqi-list-card__header">
                    <div class="cqi-list-card__icon cqi-list-card__icon--amber">
                        <i class="bi bi-exclamation-triangle-fill"></i>
                    </div>
                    <h5 class="cqi-list-card__title">Areas for Improvement</h5>
                </div>
                <ul class="cqi-bullet-list">
                    @foreach ($ai['areas_for_improvement'] as $a)
                        <li class="cqi-bullet-list__item cqi-bullet-list__item--amber">
                            {{ $a }}
                        </li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
    @endif

</div>

{{-- ===== ACTION PLAN ===== --}}
@if (!empty($ai['action_plan']))
<div class="card mb-4">
    <div class="card-body">
        <div class="cqi-list-card__header mb-3">
            <div class="cqi-list-card__icon cqi-list-card__icon--blue">
                <i class="bi bi-list-task"></i>
            </div>
            <h5 class="cqi-list-card__title">Action Plan</h5>
        </div>
        <div class="table-responsive">
            <table class="table data-table align-middle mb-0">
                <thead>
                    <tr>
                        <th>Area</th>
                        <th>Action</th>
                        <th>Responsible</th>
                        <th>Timeline</th>
                        <th>Expected Outcome</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($ai['action_plan'] as $ap)
                    <tr>
                        <td>
                            <span class="category-tag">{{ $ap['area'] }}</span>
                        </td>
                        <td style="font-size:.875rem;">{{ $ap['action'] }}</td>
                        <td class="text-muted-sm">{{ $ap['responsible_person'] }}</td>
                        <td>
                            <span class="timeline-badge">
                                <i class="bi bi-clock me-1"></i>{{ $ap['timeline'] }}
                            </span>
                        </td>
                        <td class="text-muted-sm">{{ $ap['expected_outcome'] }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endif

{{-- ===== CONCLUSION ===== --}}
@if (isset($ai['conclusion']))
<div class="cqi-section cqi-section--conclusion mb-4">
    <div class="cqi-section__header">
        <div class="cqi-section__icon cqi-section__icon--navy">
            <i class="bi bi-journal-check"></i>
        </div>
        <h3 class="cqi-section__title">Conclusion</h3>
    </div>
    <p class="cqi-section__body">{{ $ai['conclusion'] }}</p>
</div>
@endif

{{-- ===== ACTIVITY LOG ===== --}}
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Activity Log</h5>
        @if ($cqiReport->logs->isEmpty())
            <p class="text-muted-sm">No log entries yet.</p>
        @else
            <div class="cqi-activity-log">
                @foreach ($cqiReport->logs as $log)
                <div class="cqi-log-row">
                    <div class="cqi-log-row__dot"></div>
                    <div class="cqi-log-row__body">
                        <div class="d-flex align-items-center gap-2 flex-wrap mb-1">
                            <span class="cqi-log-action">
                                {{ str_replace('_', ' ', $log->action) }}
                            </span>
                            <span class="text-muted-sm">by {{ $log->performedBy?->name }}</span>
                        </div>
                        @if ($log->notes)
                            <p class="cqi-log-row__notes">{{ $log->notes }}</p>
                        @endif
                        <span class="cqi-log-row__time">
                            <i class="bi bi-clock me-1"></i>
                            {{ $log->created_at->format('M d, Y h:i A') }}
                        </span>
                    </div>
                </div>
                @endforeach
            </div>
        @endif
    </div>
</div>

@endsection

@push('scripts')
<script src="{{ asset('js/modules/confirm-action.js') }}"></script>
@endpush