@extends('admin.layouts.app')
@section('title', 'CQI Report')

@section('content')
<div class="page-header">
    <h1>CQI Report</h1>
    <div class="actions">
        <a href="{{ route('admin.cqi-reports.download', $cqiReport->id) }}" class="btn btn-primary">↓ Download PDF</a>
        <form method="POST" action="{{ route('admin.cqi-reports.send-to-faculty', $cqiReport->id) }}">
            @csrf
            <button class="btn btn-success">Mark Sent to Faculty</button>
        </form>
        <a href="{{ route('admin.cqi-reports.index') }}" class="btn btn-secondary">← Back</a>
    </div>
</div>

{{-- Report meta --}}
<div class="card" style="margin-bottom:1.25rem;">
    <div class="card-body">
        <table style="font-size:.875rem;width:100%;">
            <tr>
                <td style="color:#6b7280;width:150px;padding:.3rem 0;">Title</td>
                <td style="font-weight:600;">{{ $cqiReport->title }}</td>
            </tr>
            <tr>
                <td style="color:#6b7280;padding:.3rem 0;">Faculty</td>
                <td>{{ $cqiReport->faculty?->name ?? '—' }}</td>
            </tr>
            <tr>
                <td style="color:#6b7280;padding:.3rem 0;">Course</td>
                <td>{{ $cqiReport->survey?->offering?->subject?->course_code }} — {{ $cqiReport->survey?->offering?->subject?->name }}</td>
            </tr>
            <tr>
                <td style="color:#6b7280;padding:.3rem 0;">Semester</td>
                <td>{{ $cqiReport->survey?->offering?->semester?->full_label }}</td>
            </tr>
            <tr>
                <td style="color:#6b7280;padding:.3rem 0;">Scope</td>
                <td><span style="text-transform:uppercase;font-size:.78rem;font-weight:600;">{{ $cqiReport->scope_type }}</span></td>
            </tr>
            <tr>
                <td style="color:#6b7280;padding:.3rem 0;">AI Model</td>
                <td style="font-size:.82rem;">{{ $cqiReport->model_name }} / {{ $cqiReport->model_version }}</td>
            </tr>
            <tr>
                <td style="color:#6b7280;padding:.3rem 0;">Generated By</td>
                <td>{{ $cqiReport->generatedBy?->name }} · {{ $cqiReport->created_at->format('M d, Y h:i A') }}</td>
            </tr>
        </table>
    </div>
</div>

@php $ai = $cqiReport->report_text; @endphp

{{-- Overall interpretation --}}
@if (isset($ai['overall_interpretation']))
<div class="card" style="margin-bottom:1rem;border-left:4px solid #4f46e5;">
    <div class="card-body">
        <p style="font-size:.925rem;color:#374151;line-height:1.6;">{{ $ai['overall_interpretation'] }}</p>
    </div>
</div>
@endif

<div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin-bottom:1rem;">

    {{-- Strengths --}}
    @if (!empty($ai['strengths']))
    <div class="card">
        <div style="padding:.65rem 1rem;background:#f0fdf4;border-bottom:1px solid #bbf7d0;font-weight:600;font-size:.875rem;color:#065f46;">✓ Strengths</div>
        <div class="card-body">
            @foreach ($ai['strengths'] as $s)
                <p style="font-size:.875rem;padding:.25rem 0;border-bottom:1px solid #f3f4f6;">• {{ $s }}</p>
            @endforeach
        </div>
    </div>
    @endif

    {{-- Areas for improvement --}}
    @if (!empty($ai['areas_for_improvement']))
    <div class="card">
        <div style="padding:.65rem 1rem;background:#fef2f2;border-bottom:1px solid #fecaca;font-weight:600;font-size:.875rem;color:#b91c1c;">⚠ Areas for Improvement</div>
        <div class="card-body">
            @foreach ($ai['areas_for_improvement'] as $a)
                <p style="font-size:.875rem;padding:.25rem 0;border-bottom:1px solid #f3f4f6;">• {{ $a }}</p>
            @endforeach
        </div>
    </div>
    @endif
</div>

{{-- Action plan --}}
@if (!empty($ai['action_plan']))
<div class="card" style="margin-bottom:1rem;">
    <div style="padding:.75rem 1rem;background:#f9fafb;border-bottom:1px solid #e5e7eb;font-weight:600;font-size:.875rem;">Action Plan</div>
    <table>
        <thead>
            <tr><th>Area</th><th>Action</th><th>Responsible</th><th>Timeline</th><th>Expected Outcome</th></tr>
        </thead>
        <tbody>
            @foreach ($ai['action_plan'] as $ap)
            <tr>
                <td style="font-size:.82rem;">{{ $ap['area'] }}</td>
                <td style="font-size:.82rem;">{{ $ap['action'] }}</td>
                <td style="font-size:.82rem;">{{ $ap['responsible_person'] }}</td>
                <td style="font-size:.82rem;">{{ $ap['timeline'] }}</td>
                <td style="font-size:.82rem;">{{ $ap['expected_outcome'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endif

{{-- Conclusion --}}
@if (isset($ai['conclusion']))
<div class="card" style="margin-bottom:1.25rem;">
    <div style="padding:.65rem 1rem;background:#f9fafb;border-bottom:1px solid #e5e7eb;font-weight:600;font-size:.875rem;">Conclusion</div>
    <div class="card-body">
        <p style="font-size:.9rem;color:#374151;line-height:1.7;">{{ $ai['conclusion'] }}</p>
    </div>
</div>
@endif

{{-- Activity log --}}
<div class="card">
    <div style="padding:.75rem 1rem;background:#f9fafb;border-bottom:1px solid #e5e7eb;font-weight:600;font-size:.875rem;">Activity Log</div>
    @if ($cqiReport->logs->isEmpty())
        <p class="empty-state" style="padding:1.5rem;">No log entries.</p>
    @else
        <table>
            <thead><tr><th>Action</th><th>Performed By</th><th>Notes</th><th>Timestamp</th></tr></thead>
            <tbody>
                @foreach ($cqiReport->logs as $log)
                <tr>
                    <td><span style="background:#e0e7ff;color:#3730a3;padding:.15rem .5rem;border-radius:4px;font-size:.75rem;font-weight:600;text-transform:uppercase;">{{ str_replace('_',' ',$log->action) }}</span></td>
                    <td style="font-size:.82rem;">{{ $log->performedBy?->name }}</td>
                    <td style="font-size:.82rem;color:#6b7280;">{{ $log->notes ?? '—' }}</td>
                    <td style="font-size:.78rem;color:#9ca3af;">{{ $log->created_at->format('M d, Y h:i A') }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @endif
</div>
@endsection
